### ISSUE TITLE
[CLI] "db upgrade --connect" does not support URL-encoded passwords

### ISSUE THREAD

**Issue by cedx** [stablekernel/aqueduct#606]
If I provide these database settings using a `database.yaml` file:

```yaml
username: postgres
password: Foo@Bar@       # Note the "at" signs!
host: foobar.com
port: 5432
databaseName: foo_bar
```
And run the `aqueduct db upgrade` command, everything is fine (i.e. the migration is applied).
But if I use the `--connect` option, I must URL-encode special characters, and I finally get this error:

```shell
$ aqueduct db upgrade --connect=postgres://postgres:Foo%40Bar%40@foobar.com:5432/foo_bar
# *** There was an error connecting to the database 'postgres:Foo%40Bar%40@foobar.com:5432/foo_bar'. Reason: unable to connect to database.
```

If I use "standard" characters (i.e. only letters and digits) for the password, the `--connect` option works as expected.
