### ISSUE TITLE
Database config: use one file for upgrade and connection

### ISSUE THREAD

**Issue by suragch** [stablekernel/aqueduct#694]
When connecting to the database you can use a `config.yaml` file like this:

```
database:
  host: localhost
  port: 5432
  username: heroes_user
  password: password
  databaseName: heroes
```

But when [upgrading the database](http://aqueduct.io/docs/db/db_tools/), if you want to specify the same information from a file you have to create a different `database.yaml` file. This creates two sources of truth and is another file that needs to be added to .gitignore.

It would be nicer to be able to use the original `config.yaml` file. Something like this:

```
aqueduct db upgrade --connect config.yaml
```

**Comment by joeconwaystk** [comment]
One challenge is that you might have multiple databases, your database key can be arbitrary, etc. One solution might be to specify a key-path alongside the config file. Example using your config file as shown:

```
aqueduct db upgrade --database-config config.yaml --keypath database
```

And then if you had a more deeply nested configuration file, you could specify a keypath like `databases.user`. Config file might look like:

```yaml
databases:
  user:
    host: localhost
    ...
```
```
