### ISSUE TITLE
Here's how to fix your Heroku app (SSL)

### ISSUE THREAD

**Issue by Eddydpyl** [stablekernel/aqueduct#959]
My Heroku instance suddenly stopped accepting connections to the DB without an SSL certificate, and so my application stopped working. Just in case someone else bumps into this problem, here's what I did:
- Update your pubspec.yaml to point to [this repo](https://github.com/darter/aqueduct) instead of the latest version of Aqueduct. Props to [NayanJD](https://github.com/NayanJD) for his [pull request](https://github.com/stablekernel/aqueduct/pull/894). Remember to add a dependency_overrides section. You might also need to set publish_to to none.
- In the channel.dart file, the one inside of your own project, within the contextWithConnectionInfo method, set the useSSL option in the PostgreSQLPersistentStore constructor to true.
- Add the --use-ssl option to the release command in Procfile.

**Comment by marciotrix77** [comment]
Thank you very much. I had the same problem and your issue saved me.

In my case, I followed the guidelines of the last two items of your solution.

I just don't know how to point pubspech.yaml to a specific repo. If you can guide me, I thank you.

Best regards.

**Comment by Eddydpyl** [comment]
Happy to help. Here's part of my pubspec:
```yaml
publish_to: none

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct:
    git:
      url: git://github.com/darter/aqueduct.git
      path: aqueduct

dev_dependencies:
  aqueduct_test: ^1.0.0

dependency_overrides:
  aqueduct: 3.3.0+1
```
